Repository rajkaste/Technical-Writeups, pull requests merged in 2022-10, with the labels that each got.

#1 links to writeups under different vulnerability category
  Cybersecurity writeups/Phone verification bypass/links.txt
  Cybersecurity writeups/XSS/links.txt
Labels: enhancement, good first issue, hacktoberfest-accepted

#2 Development writeups directory created
  Developement writeups/Big Data/data-engineer-links.txt.txt
Labels: documentation, enhancement, hacktoberfest-accepted

#3 Blogs for Frontend dev added
  Developement writeups/Frontend Dev/Frontend blog links.txt
Labels: documentation, good first issue, hacktoberfest-accepted

#4 Added links to XSS writeup
  Cybersecurity writeups/XSS/links.txt
Labels: documentation, enhancement, hacktoberfest-accepted

#5 Importance of Hooks in React added
  Developement writeups/Frontend Dev/WhyHooksInReact.txt
Labels: documentation, hacktoberfest-accepted

#6 Update README.md
  README.md
Labels: documentation, enhancement, hacktoberfest-accepted
